version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    REPOSITORY_URI: 792157736433.dkr.ecr.ap-south-1.amazonaws.com/mohit-kubernetes
    IMAGE_REPO_NAME: mohit-kubernetes
    CONTAINER_NAME: mohit-kubernetes

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - set -e
      - mvn -version

  pre_build:
    commands:
      - set -e
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 792157736433.dkr.ecr.ap-south-1.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - |
        aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --region $AWS_REGION || \
        aws ecr create-repository --repository-name $IMAGE_REPO_NAME --region $AWS_REGION

  build:
    commands:
      - set -e
      - mvn clean install -DskipTests
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - set -e
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/*.jar